version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "asset-api"
s3_bucket = "ampflask-serverless-deploy-bucket"
s3_prefix = "uiapi"
region = "us-west-2"
profile = "ryan_sandbox"
capabilities = "CAPABILITY_IAM"
image_repositories = []
